SUBROUTINE PARAM1_PY(X, Y, I1, I2)
IMPLICIT NONE
INTERFACE
   SUBROUTINE PARAM1(X, Y)
      REAL(KIND=8), DIMENSION(:,:), INTENT(IN) :: X
      REAL(KIND=8), DIMENSION(:,:), INTENT(OUT) :: Y
   END SUBROUTINE PARAM1
END INTERFACE
INTEGER(KIND=8), INTENT(IN) :: I1, I2
REAL(KIND=8), INTENT(IN), DIMENSION(I1, I2) :: X
REAL(KIND=8), INTENT(OUT), DIMENSION(I1, I2) :: Y
CALL PARAM1(X, Y)
END SUBROUTINE PARAM1_PY

SUBROUTINE PARAM2_PY(X, Y, I1, I2)
IMPLICIT NONE
INTERFACE
   SUBROUTINE PARAM2(X, Y)
      REAL(KIND=8), DIMENSION(:,:), INTENT(IN) :: X
      REAL(KIND=8), DIMENSION(:,:), INTENT(OUT) :: Y
   END SUBROUTINE PARAM2
END INTERFACE
INTEGER(KIND=8), INTENT(IN) :: I1, I2
REAL(KIND=8), INTENT(IN), DIMENSION(I1, I2) :: X
REAL(KIND=8), INTENT(OUT), DIMENSION(I1, I2) :: Y
CALL PARAM2(X, Y)
END SUBROUTINE PARAM2_PY
