SUBROUTINE INIT(ICONF)
IMPLICIT NONE
INTEGER(KIND=8), INTENT(IN) :: ICONF
!Here we could set in a module values 1 and 0.9 used afterwards, for example
!Actual values may depend on the value of ICONF...
END SUBROUTINE INIT

SUBROUTINE PARAM1(X, Y)
IMPLICIT NONE
REAL(KIND=8), INTENT(IN), DIMENSION(:, :) :: X
REAL(KIND=8), INTENT(OUT), DIMENSION(:, :) :: Y
Y=X+1
IF(Y(1,1)==-99999999) PRINT*, Y ! To force linking with a compiler specific lib
END SUBROUTINE PARAM1

SUBROUTINE PARAM2(X, Y)
IMPLICIT NONE
REAL(KIND=8), INTENT(IN), DIMENSION(:, :) :: X
REAL(KIND=8), INTENT(OUT), DIMENSION(:, :) :: Y
Y=X+.9
END SUBROUTINE PARAM2
